### ISSUE TITLE
34的服务中为什么返回00300002

### ISSUE THREAD

**Issue by kobewang126** [Gitlittlerubbish/YA-DoIP#1]
请问在34的服务中，为什么返回00300002，然后client端又-2，这样子操作的好处是什么，为什么不直接返回00300000
self._block_len_max = int.from_bytes(self._current_uds_payload, 'big', signed=False) - 2

**Comment by Gitlittlerubbish** [comment]
感谢您的issue！抱歉很久没有看到本仓库了，这里的操作时无所谓的，我是为了快速实现这个工具在34服务中做了这个操作，实际上只要stack和client配套就行，这个是无所谓的。
